Logic Implementation
Jarfsoft/react_calculator pull request #4
Opened 2021-06-03 17:01 UTC by Jarfsoft

**Feature added:**

- Logic implementation
- Styles to buttons
- Styles to Display

2021-06-03 18:45 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi @Jarfsoft, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-06-03 18:45 UTC, arslanbisharat commented on src/Components/App.js
>    const [data, setData] = useState({
- [ ] App is converted to a stateful component using class ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/app/stateful.png))
- [ ] App has state initialized in constructor ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/app/stateful.png))
- [ ] App has `handleClick` implemented in constructor

```javascript
constructor(props) {
  super(props);
  this.state = {
      total: null,
      next: null,
      operation: null,
  };
  }

  handleClick = (buttonName) => {
  this.setState(calculate(this.state, buttonName));
  }
}
```

- [ ] App passes `handleClick` as a `clickHandler` property to `ButtonPanel` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/app/passHandleClick.png))
- [ ] App passes the `total` or `next` value from state to `Display` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/app/passToatalToDisplay.png))

2021-06-03 18:45 UTC, arslanbisharat commented on src/Components/Button.js
>  export default Button;
- [ ] Button attaches `handleClick` to `onClick` event on Button

2021-06-03 18:45 UTC, arslanbisharat commented on src/Components/ButtonPanel.js
> +      </>
- [ ] ButtonPanel implements `handleClick` function ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/panel/implementHandleClick.png))

```javascript
handleClick = (buttonName) => {
  this.props.clickHandler(buttonName);
};
```

- [ ] ButtonPanel passes `handleClick` as `clickHandler` props to each `Button` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/panel/passToButton.png))

2021-06-04 06:31 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes.
`App` component turned into a class component as requested. Well done.
### Change to be made 🙅🏿 🙅🏿 🙅🏿 
- Remove comments from your code.

### Martin Afani
#### Slack: whiz25

2021-06-04 06:31 UTC, afanimartin commented on src/Components/App.js
> +  // );
- Remove this comment.

2021-06-04 12:50 UTC, Torres-ssf approved these changes
### Milestone Approved :+1: 
Hello @Jarfsoft 
Nice job on this milestone
Good luck with the next one

Happy coding :computer: 
**Sérgio Torres**

2021-06-04 12:54 UTC, merged